name: tf_gpu_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - abseil-cpp=20210324.2
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - astor=0.8.1
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.2
  - bottleneck=1.3.7
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cryptography=41.0.3
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - cycler=0.12.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - fonttools=4.53.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - graphviz=2.38
  - grpcio=1.42.0
  - h5py=3.11.0
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=68.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib-resources=6.4.0
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2021.4.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jbig=2.1
  - jedi=0.19.1
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.5
  - lcms2=2.12
  - lerc=2.2.1
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libclang=11.1.0
  - libcurl=8.7.1
  - libdeflate=1.7
  - libpng=1.6.39
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.4
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.4
  - numpy=1.23.3
  - numpy-base=1.23.3
  - oauthlib=3.2.2
  - olefile=0.47
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=24.1
  - pandas=1.4.4
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=24.0
  - platformdirs=3.10.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.47
  - protobuf=3.17.2
  - psutil=6.0.0
  - pure_eval=0.2.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=5
  - pycparser=2.21
  - pydot=1.4.1
  - pygments=2.18.0
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.2
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.9.0post0
  - python_abi=3.9
  - pytz=2024.1
  - pywin32=306
  - pyzmq=26.0.3
  - qhull=2020.2
  - qt=5.12.9
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - scikit-learn=1.4.2
  - scipy=1.10.1
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - tensorflow-gpu=2.6.0
  - termcolor=2.1.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - werkzeug=3.0.3
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wrapt=1.14.1
  - xz=5.2.6
  - yarl=1.9.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.0
  - pip:
      - absl-py==0.10.0
      - cachetools==4.2.4
      - clang==5.0
      - dm-tree==0.1.8
      - flatbuffers==1.12
      - google-auth==1.32.1
      - mysql-connector-python==9.0.0
