@startuml RecommendationSystem
!define RECTANGLE class
skinparam packageBackgroundColor #DDDDDD
skinparam classBackgroundColor #EEEEEE

package "RecommendationSystem" {
    package "prediction_main"{
        package "recommendation_model" {
            RECTANGLE PredictionProcessor {
                +predict_for_user()
                +preprocess_data()
                -preprocess_and_predict_batch()
            }
        }
    }
    
    package "data_management" {
        RECTANGLE MySQLDatabase {
            +connect()
            +execute_query()
            +get_features_by_user_id()
            +close()
        }
        
        RECTANGLE FileManage {
            +file_paths: json
            +initialize_paths()
            +load_paths()
            +read_files()
            +save_processed_data()
            +load_from_joblib()
        }
    }


    package "feature_processing" {
        RECTANGLE NumericProcessor {
            +user_features()
        }

        RECTANGLE ContextualProcessor {
            +clean_contextual_features()
        }

        RECTANGLE FeatureProcessor {
            +one_hot_encoder()
            +one_hot_encode_contextual_features()
            +one_hot_encode_gender_features()
            -get_or_create_encoder()
        }
    }
}

package music_database <<Database>> {
    ' Empty package, just to indicate the existence of the database
}

PredictionProcessor --> FileManage : " uses"
PredictionProcessor --> ContextualProcessor : " uses"
PredictionProcessor --> FeatureProcessor : " uses"
PredictionProcessor --> NumericProcessor : " uses"
PredictionProcessor --> MySQLDatabase : " uses"
MySQLDatabase --> music_database : "  interacts with"

@enduml
